<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20141008183910 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE achimfritz_documents_domain_model_documentcollection (persistence_object_identifier VARCHAR(40) NOT NULL, category VARCHAR(40) DEFAULT NULL, INDEX IDX_CC71634D64C19C1 (category), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_documents_domain_model_document_categories_join (documents_document VARCHAR(40) NOT NULL, documents_category VARCHAR(40) NOT NULL, INDEX IDX_662B8F80B1F004E9 (documents_document), INDEX IDX_662B8F806FD5975E (documents_category), PRIMARY KEY(documents_document, documents_category)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE achimfritz_documents_domain_model_documentcollection ADD CONSTRAINT FK_CC71634D64C19C1 FOREIGN KEY (category) REFERENCES achimfritz_documents_domain_model_category (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_documents_domain_model_document_categories_join ADD CONSTRAINT FK_662B8F80B1F004E9 FOREIGN KEY (documents_document) REFERENCES achimfritz_documents_domain_model_document (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_documents_domain_model_document_categories_join ADD CONSTRAINT FK_662B8F806FD5975E FOREIGN KEY (documents_category) REFERENCES achimfritz_documents_domain_model_category (persistence_object_identifier)");
		$this->addSql("DROP TABLE achimfritz_documents_domain_model_category_documents_join");
		$this->addSql("DROP TABLE achimfritz_documents_domain_model_containerdiff");
		$this->addSql("DROP TABLE achimfritz_documents_domain_solr_facet");
		$this->addSql("DROP TABLE achimfritz_documents_domain_solr_facetcontainer");
		$this->addSql("DROP INDEX flow_identity_achimfritz_documents_domain_model_category ON achimfritz_documents_domain_model_category");
		$this->addSql("ALTER TABLE achimfritz_documents_domain_model_category DROP dtype");
		$this->addSql("DROP INDEX flow_identity_achimfritz_documents_domain_model_document ON achimfritz_documents_domain_model_document");
		$this->addSql("ALTER TABLE achimfritz_documents_domain_model_document ADD documentcollection VARCHAR(40) DEFAULT NULL, DROP dtype");
		$this->addSql("ALTER TABLE achimfritz_documents_domain_model_document ADD CONSTRAINT FK_561187EDA3E9EC8E FOREIGN KEY (documentcollection) REFERENCES achimfritz_documents_domain_model_documentcollection (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_561187EDA3E9EC8E ON achimfritz_documents_domain_model_document (documentcollection)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_documents_domain_model_document DROP FOREIGN KEY FK_561187EDA3E9EC8E");
		$this->addSql("CREATE TABLE achimfritz_documents_domain_model_category_documents_join (documents_category VARCHAR(40) NOT NULL, documents_document VARCHAR(40) NOT NULL, INDEX IDX_8771F2886FD5975E (documents_category), INDEX IDX_8771F288B1F004E9 (documents_document), PRIMARY KEY(documents_category, documents_document)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_documents_domain_model_containerdiff (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, diff INT NOT NULL, countfirst INT NOT NULL, countsecond INT NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_documents_domain_solr_facet (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, countofdocuments INT NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_documents_domain_solr_facetcontainer (persistence_object_identifier VARCHAR(40) NOT NULL, facets VARCHAR(255) NOT NULL, countofdocuments INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE achimfritz_documents_domain_model_category_documents_join ADD CONSTRAINT FK_8771F2886FD5975E FOREIGN KEY (documents_category) REFERENCES achimfritz_documents_domain_model_category (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_documents_domain_model_category_documents_join ADD CONSTRAINT FK_8771F288B1F004E9 FOREIGN KEY (documents_document) REFERENCES achimfritz_documents_domain_model_document (persistence_object_identifier)");
		$this->addSql("DROP TABLE achimfritz_documents_domain_model_documentcollection");
		$this->addSql("DROP TABLE achimfritz_documents_domain_model_document_categories_join");
		$this->addSql("ALTER TABLE achimfritz_documents_domain_model_category ADD dtype VARCHAR(255) NOT NULL");
		$this->addSql("CREATE UNIQUE INDEX flow_identity_achimfritz_documents_domain_model_category ON achimfritz_documents_domain_model_category (path)");
		$this->addSql("DROP INDEX IDX_561187EDA3E9EC8E ON achimfritz_documents_domain_model_document");
		$this->addSql("ALTER TABLE achimfritz_documents_domain_model_document ADD dtype VARCHAR(255) NOT NULL, DROP documentcollection");
		$this->addSql("CREATE UNIQUE INDEX flow_identity_achimfritz_documents_domain_model_document ON achimfritz_documents_domain_model_document (name)");
	}
}