<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20141216195214 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE achimfritz_documents_domain_model_documentlist (persistence_object_identifier VARCHAR(40) NOT NULL, category VARCHAR(40) DEFAULT NULL, INDEX IDX_5576BB2964C19C1 (category), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_documents_domain_model_documentlistitem (persistence_object_identifier VARCHAR(40) NOT NULL, documentlist VARCHAR(40) DEFAULT NULL, document VARCHAR(40) DEFAULT NULL, sorting INT NOT NULL, INDEX IDX_694EAF50DA091306 (documentlist), INDEX IDX_694EAF50D8698A76 (document), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE achimfritz_documents_domain_model_documentlist ADD CONSTRAINT FK_5576BB2964C19C1 FOREIGN KEY (category) REFERENCES achimfritz_documents_domain_model_category (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_documents_domain_model_documentlistitem ADD CONSTRAINT FK_694EAF50DA091306 FOREIGN KEY (documentlist) REFERENCES achimfritz_documents_domain_model_documentlist (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_documents_domain_model_documentlistitem ADD CONSTRAINT FK_694EAF50D8698A76 FOREIGN KEY (document) REFERENCES achimfritz_documents_domain_model_document (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_documents_domain_model_documentlistitem DROP FOREIGN KEY FK_694EAF50DA091306");
		$this->addSql("DROP TABLE achimfritz_documents_domain_model_documentlist");
		$this->addSql("DROP TABLE achimfritz_documents_domain_model_documentlistitem");
	}
}