<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20141123162912 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_documents_domain_model_document DROP FOREIGN KEY FK_561187EDA3E9EC8E");
		$this->addSql("DROP TABLE achimfritz_documents_domain_model_documentcollection");
		$this->addSql("DROP INDEX IDX_561187EDA3E9EC8E ON achimfritz_documents_domain_model_document");
		$this->addSql("ALTER TABLE achimfritz_documents_domain_model_document DROP documentcollection");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE achimfritz_documents_domain_model_documentcollection (persistence_object_identifier VARCHAR(40) NOT NULL, category VARCHAR(40) DEFAULT NULL, INDEX IDX_CC71634D64C19C1 (category), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE achimfritz_documents_domain_model_documentcollection ADD CONSTRAINT FK_CC71634D64C19C1 FOREIGN KEY (category) REFERENCES achimfritz_documents_domain_model_category (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_documents_domain_model_document ADD documentcollection VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE achimfritz_documents_domain_model_document ADD CONSTRAINT FK_561187EDA3E9EC8E FOREIGN KEY (documentcollection) REFERENCES achimfritz_documents_domain_model_documentcollection (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_561187EDA3E9EC8E ON achimfritz_documents_domain_model_document (documentcollection)");
	}
}