<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150105175956 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		$this->addSql("ALTER TABLE achimfritz_documents_domain_model_documentlist DROP INDEX IDX_5576BB2964C19C1, ADD UNIQUE INDEX UNIQ_5576BB2964C19C1 (category)");
		
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		$this->addSql("ALTER TABLE achimfritz_documents_domain_model_documentlist DROP INDEX UNIQ_5576BB2964C19C1, ADD INDEX IDX_5576BB2964C19C1 (category)");
		
	}
}
