<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150303082116 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_documents_domain_model_filesystemdocument ADD filehash VARCHAR(255) NOT NULL");
		$this->addSql("CREATE UNIQUE INDEX flow_identity_achimfritz_documents_domain_model_filesyste_4a889 ON achimfritz_documents_domain_model_filesystemdocument (filehash)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP INDEX flow_identity_achimfritz_documents_domain_model_filesyste_4a889 ON achimfritz_documents_domain_model_filesystemdocument");
		$this->addSql("ALTER TABLE achimfritz_documents_domain_model_filesystemdocument DROP filehash");
	}
}
