<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20141122165209 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE achimfritz_documents_domain_model_filesystemdocument (persistence_object_identifier VARCHAR(40) NOT NULL, relativepath VARCHAR(255) NOT NULL, mountpoint VARCHAR(255) NOT NULL, mdatetime DATETIME NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE achimfritz_documents_domain_model_filesystemdocument ADD CONSTRAINT FK_8D542CF047A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_documents_domain_model_document (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE achimfritz_documents_domain_model_document ADD dtype VARCHAR(255) NOT NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP TABLE achimfritz_documents_domain_model_filesystemdocument");
		$this->addSql("ALTER TABLE achimfritz_documents_domain_model_document DROP dtype");
	}
}