AchimFritz:
  Documents:
    solr:
      hostname: localhost
      port: 8080
      path: solr4/documents
      servlet: select
    export: /tmp
    fileSystemDocument:
      mountPoint: /
      webPath: 
    mp3Document:
      mountPoint: /mp3/db
      webPath: mp3
    imageDocument:
      usbMountPoint: /mnt/sdd1
      mountPoint: /bilder/main
      backupPath: /bilder/orig
      geeqieMetadataPath: /data/home/af/.local/share/geeqie/metadata/bilder/main/
      export: /bilder/export
      webPath: thumbs/1280x1024
      webThumbPath: thumbs/64x48
      webBigPath: thumbs/800x600
      webPreviewPath: thumbs/320x240
